#!/bin/bash

function unmount {
  umount $boot_partition
  umount $root_partition
}

function partition {
  unmount

  parted -a optimal -s $target_disk mklabel msdos
  parted -a optimal -s $target_disk mkpart primary fat32 0% 100MiB
  parted -a optimal -s $target_disk mkpart primary ext4 100MiB 100%
  parted -a optimal -s $target_disk set 2 lba off
}

function format {
  unmount

  mkfs.vfat $boot_partition
  mkfs.ext4 -F $root_partition
}

function install {
  mkdir boot
  mount $boot_partition boot

  mkdir root
  mount $root_partition root

  curl -L http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz | bsdtar -xpf- -C root
  sync

  mv root/boot/* boot

  unmount
}

echo "Starting"

target_disk="$1"
boot_partition="$target_disk"1
root_partition="$target_disk"2

partition
format
install
