#!/bin/bash

function partition {
  boot_partition="$target_disk"1
  root_partition="$target_disk"2

  umount $target_disk

  echo "
  o
  n
  p
  1

  +100M
  Y
  t
  c
  n
  p
  2
  Y

  w
  " | fdisk $target_disk

  umount $target_disk

  mkfs.vfat -F $boot_partition
  mkdir boot
  mount $boot_portition boot

  mkfs.ext4 -F $root_partition
  mkdir root
  mount $root_partition root
}

function install {
  curl -L http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz | bsdtar -xpf- -C root
  sync

  mv root/boot/* boot
  umount boot root
}

echo "Starting"

target_disk="$1"

partition
install
